services:
  backend:
    container_name: backend
    image: cliqueur/backend
    build:
      context: backend
      platforms:
        - "linux/amd64"
    env_file: backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models

  frontend:
    container_name: frontend
    image: cliqueur/frontend
    build:
      context: frontend
    ports:
      - "3000:3000"
